# Generated by Django 3.1.4 on 2021-01-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('priority', models.CharField(max_length=10)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
